### ISSUE TITLE
Biocatalyst:Adding cell free production system

### ISSUE THREAD

**Issue by StephanM87** [Strenda-biocatalysis/Strenda-biocatalysis#16]
Exchange cell-free production with cell-free 

## Exchange title of non-immobilised biocatalysts: 
- Production procedure
- Immobilisation procedure
- Combinatorial procedure

Change the catalogue to:

1. identity of the catalyst
- - Formulations available (cell free, immobilised etc.)

**Comment by KatrinRosenthal** [comment]
Rename Cell-free production in Cell-free protein synthesis (CFPS)

**Comment by KatrinRosenthal** [comment]
I went through the whole list again. We did not include the production of the biocatalyst at any point (growth or expression conditions, harvest time, etc.). Had we decided against it? We might then have to discuss the CFPS again, since it is also just a protein production method.

**Comment by PeterHalling** [comment]
Yes, I agree, CFPS is exactly one method of biocatalyst production, one that should actually give a protein of well-defined identity.

**Comment by PeterHalling** [comment]
We still have Cell Free Production in a list of biocatalyst forms. But as Katrin said, this is actually a method of biocatalyst production, so should go in the section Biocatalyst Self-Produced. As she points out, we don't have a lot of detail there for other methods of production, e.g. fermentation of cells expressing the enzyme(s). But we do need to be cautious in telling people what is needed to properly describe a fermentation process, because we are not the experts here (at least I'm not!).
